config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  devise_for :users, :controllers => { omniauth_callbacks: "callbacks"}

  post '/users/id:/players', to: 'players#create'
  
  # resources :matches
  resources :users do 
    resources :players
      resources :matches
    end
    get '/players/in_order', to: 'players#in_order', as: 'in_order'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :matches, dependent: :destroy
    has_many :users, through: :matches

    scope :in_order, -> {where("LENGTH(name) < 10")}
    validates :name, presence:{message: "A player must have a name!"}
    validates :player_number, presence:true
    accepts_nested_attributes_for :matches

end

app/models/user.rb
class User < ApplicationRecord
  has_many :matches
  has_many :players, through: :matches
  
  # has_many
  # Is plural
  # Sets up a many-to-many association using another model
  # The matchplayer would have both a 'match_id' && 'player_id'

  attr_reader :password
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    end     
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
    # helper_method :current_user

    # def authorize
    #     redirect_to new_user_session_path, alert: 'WHOA THERE BUDDY... Dont make me call Flatiron Police o_O' if current_user.nil?
    # end

    def home
        @user = current_user ? current_user.email.split("@")[0]:nil
        # @user = current_user ? current_user.read_attribute(attribute_name)
    end
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect(@user)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    before_action :find_match, only:[:show, :edit, :update, :destroy]
    # before_action :authorize, except: []
    # before_action :only_see, except: []
    #show /show all page
    def index
        # byebug
        @matches = Match.all
    end

    #Get /read action for a single object
    def show 
    end         

    #Post /create action
    def create 
        # byebug
        @player = Player.find(params[:player_id])
        @match = @player.match.create(match_params)
        @match.user_id = current_user.id
        if @match.valid?
            @match.save
            redirect_to user_match_path(current_user, @match.id)
        else
            @errors = @match.errors.full_messages
            render :new
        end
    end

    #Get /render new form
    def new
        # byebug
        @user = current_user
        @match = Match.new
        # 4.times{@match.players.build}
    end

    #Get /edit form 
    def edit
    end

    #Post /update action
    def update
        @match.update(params.require(:match).permit(:valid_match))
        redirect_to user_match_path(@match.id)    
    end 

    #Post /destroy action
    def destroy 
        @match.destroy
        redirect_to user_matches_path
    end

    private
    def match_params
        params.require(:match).permit(:id, :valid_match, :user_id, :player_id)
    end

    def find_match
        @match = Match.find(params[:id])
    end

    def only_see
        @match != current_user.matches
        redirect_to new_user_match_path
    end
    
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :find_player, only:[:show, :edit, :update, :destroy]
    # before_action :authorize, except: []
    #show /show all page
    def index
        @players = Player.all
        # @player = current_user.players
    end

    def in_order
        @players = Player.in_order 
    end

    #Get /read action for a single object
    def show 
    end 
        
    
    #Post /create action
    def create 
        @player = Player.new(player_params)
        # Assign all matches to the current user
        @player.matches.each do |match|
          match.user = current_user
        end

        if @player.save
            redirect_to user_player_path(current_user, @player.id)
            # redirect_to user_match_path(current_user, @match)
        else
            @errors = @player.errors.full_messages
            render :new  
        end    
    end
    
    #Get /render new form
    def new
        @player = Player.new
        @player.matches.build
        @player.save
    end
    
    #Get /edit form 
    def edit
    end
    
    #Post /update action
    def update
        @player.update(player_params)
        redirect_to user_player_path(@player.id)
    end 
    
    #Post /destroy action
    def destroy 
        @player.destroy
        redirect_to user_players_path
    end

    private
    def player_params
        params.require(:player).permit(:name, :player_number, :starter, matches_attributes:[:id, :valid_match])
    end

    def find_player
        @player = Player.find(params[:id])
    end
    #Getting infinite loop

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<% if user_signed_in? %>
<h1>Welcome <%= @user %></h1>
<h3>What would you like to look at?</h3>

<ul>
    <li><%= link_to "Players", user_players_path(current_user), {method: 'get'} %></li>
</ul>
<div>
    <%= button_to "Log Out", destroy_user_session_path , method: :delete %>
</div>
<%end%>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.html.erb
<nav>
<% if !user_signed_in?%>
    <h1>Welcome To Tournament Creator!</h1>
    <ul>
        <li> <%= link_to "Sign Up", new_user_registration_path %></li>
        <li> <%= link_to "Log In", new_user_session_path %></li>
        <li> <%= link_to "Log In w/ Github", user_github_omniauth_authorize_path %></li>
<% else %>
        <div> 

        </div>
    <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TournamentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'layouts/alerts'%>
    <%= render 'layouts/nav'%>
    <%= yield %>
    
  </body>
</html>

app/views/matches/_form.html.erb
<h1>Match:</h1>
<%= form_for(@match) do |f| %>
<%= f.label :valid_match %>
<%= f.check_box :valid_match %>

<%= f.fields_for :player do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

<%end%>
<%= f.submit "Save" %>
<%end%>

<br>
<%= link_to "Go To Matches", user_matches_path(current_user) %>
</br>
<br>
<%= link_to "Welcome Page", user_session_path %>
</br>

app/views/matches/edit.html.erb
<h1> Edit Match </h1>

<%= render 'form', match:@match %>
<br>
<%= link_to "Go Back", user_match_path %>
</br>
<br>
<%= button_to "Delete This Match", user_matches_path(@match.user, @match), method: :delete %>
</br>

app/views/matches/index.html.erb
<h1>All Matches</h1>

<ul>
    <% @matches.each do |match| %>
    <li> <%= link_to match.match_number, user_match_path(current_user, match) %> </li>
<%end%>
</ul>

<br>
<%= link_to "Create New Match", new_user_match_path(current_user) %>
</br>
<br>
<%= link_to "Go To Players", user_players_path %>
</br>
<br>
<%= link_to "Welcome Page", user_session_path %>
</br>

app/views/matches/new.html.erb
<h1>Create New Match & Players</h1>
<% if @errors && !@errors.empty?%>
    <% @errors.each do |e| %>
        <p><%= e %></p>
    <%end%>
<%end%>
<%= render 'form', match:@match %>

app/views/matches/show.html.erb
<h1>Match: <%= @match.match_number %></h1>
<h3>Match: <%= @match.match_date %></h3>

<%= f.collection_check_box player_ids, user.players, :id, :name, value: true %>

<%= 
<br>
<%= link_to "Edit This Match", edit_user_match_path(current_user) %>
</br>
<br>
<%= link_to "Go To Matches", user_matches_path(current_user) %>
</br>
<br>
<%= link_to "Go To Welcome Page", user_session_path(current_user) %>
</br>
<br>
<%= button_to "Delete This Match", user_match_path(current_user, @match), method: :delete %>
</br>

app/views/players/_form.html.erb
<%= form_for([current_user, @player]) do |f| %>
    <h2>Players:</h2>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :player_number %>
    <%= f.number_field :player_number%>
    <%= f.label :starter %>
    <%= f.check_box :starter %>
    <%= f.fields_for :matches do |ff| %>
      <%= ff.label :valid_match %>
      <%= ff.check_box :valid_match %>
    <%end%>
<%= f.submit %>
<%end%>

app/views/players/edit.html.erb
<h1> Edit Player </h1>

<%= render 'form', player:@player %>

<br>
<%= button_to "Go To Players", user_players_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Go Back To Player", user_player_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Delete This Match", user_player_path(@player), method: :delete %>
</br>
<br>
<%= button_to "Welcome Page", user_session_path, {method: 'get'} %>
</br>

app/views/players/in_order.html.erb
<h1>List of Player Names for Users with Hippopotomonstrosesquippedaliophobia</h1>
<h3>(Fear of Long Words)</h3>

<% @players.each do |player|%>
    <ul>
    <li><%= player.name %></li>
    </ul>
    <%=  %>
<%end%>

<%= button_to "All Players", user_players_path(current_user), {method: 'get'} %>

app/views/players/index.html.erb
<h1>All Players</h1>

<ul>
<% @players.each do |player| %>
    <li> <%= link_to player.name, user_player_path(current_user, player) %> <%= "#{player.player_number}" %></li>
<%end%>
</ul>

<br>
<%= button_to "Create New player", new_user_player_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Short Names", in_order_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Welcome Page", user_session_path, {method: 'get'} %>
</br>

app/views/players/new.html.erb
<h1>Create New Players</h1>
<% if @errors && !@errors.empty?%>
    <% @errors.each do |e| %>
        <p><%= e %></p>
    <%end%>
<%end%>
<%= render 'form', player:@player %>

<br>
<%= button_to "Go To Players", user_players_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Welcome Page", user_session_path, {method: 'get'} %>
</br>

app/views/players/show.html.erb
<h1>Player: <%= @player.name %></h1>
<h3>Player: <%= @player.player_number %></h3>
<h3>Starter?: <%= @player.starter ? "Yes" : "No" %></h3>

<h3>Match:</h3>
<% @player.matches.each do |match| %>
<p><%= match.valid_match ? "Yes" : "No" %></p>
<%end%>

<div>
<br>
<%= button_to "Edit This Match", edit_user_player_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Go To Players", user_players_path, {method: 'get'} %>
</br>
<br>
<%= button_to "Delete This Match", user_player_path(@player), method: :delete %>
</br>
<br>
<%= button_to "Go To Welcome Page", user_session_path, {method: 'get'} %>
</br>
</div>